extends: spectral:oas
rules:
  example-value-or-externalValue: false
  oas3-unused-components-schema: false # needed by inter-file references e.g. Voice API
  oas3-valid-content-schema-example: false
  oas3-valid-oas-content-example: false
  oas3-valid-oas-parameter-example: false
  oas3-valid-parameter-schema-example: false
  oas3-valid-schema-example: false
  openapi-tags: false
  operation-description: false
  operation-tags: false

  # Check field names meet api standards
  property-names:
    severity: warn
    message: "Invalid property name: {{value}} (expected: lowercase with underscores)"
    recommended: true
    given: "$.paths.*.*.parameters.*.name"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z_]+$"

  # Check response field names meet api standards
  response-property-names:
    severity: warn
    message: "Invalid response property name: {{property}} (expected: lowercase with underscores)"
    recommended: true
    given: "$..components.schemas.*.properties[*]~"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z_]+$"

  # Require 3-part Semantic Versions as the spec versions
  semver:
    severity: error
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version.
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+.[0-9]+.[0-9]+)$"
